version: "3.6"
services:
  digital_diary_admin:
    image: digital_diary_admin
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=host.docker.internal;Port=5432;Database=digitaldiary;Pooling=true;
    ports:
      - "3000:80"
  digital_diary:
    image: digital_diary
    build:
      context: .
      target: DigitalDiary
    environment:
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=host.docker.internal;Port=5432;Database=digitaldiary;Pooling=true;
    ports:
      - "8000:80"
  client:
    image: client
    build:
      context: client
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://94.142.141.72:8000