version: "3.6"
services:
  digital_diary_admin:
    image: digital_diary_admin
    build:
      context: .
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DIGITAL_DIARY_Email:Password=${EMAIL_PASSWORD}
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=94.142.141.72;Port=5432;Database=digitaldiary;Pooling=true;
    ports:
      - "3000:80"
  digital_diary:
    image: digital_diary
    build:
      context: .
      target: DigitalDiary
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DIGITAL_DIARY_Email:Password=${EMAIL_PASSWORD}
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=94.142.141.72;Port=5432;Database=digitaldiary;Pooling=true;
    ports:
      - "8000:80"
  client:
    image: client
    build:
      context: client
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://94.142.141.72:8000